### ISSUE TITLE
[Feature Request] Support migrating global NPM packages between Node versions

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#1]
I'm really enjoying using NVS! One thing that would be a nice addition would be the ability to migrate global NPM packages from one Node version to another, particularly as part of the process of adding a new one (e.g. `nvs add 7 --reinstall-packages` or something). I got used to this feature when using NVM, and it's pretty handy when updating Node fairly regularly.

**Comment by jasongin** [comment]
Definitely, that feature is at the top of my priority list.

**Comment by jasongin** [comment]
I pushed a [migrate](https://github.com/jasongin/nvs/tree/migrate) branch with this new functionality. The usage is explained here: https://github.com/jasongin/nvs/blob/migrate/doc/MIGRATE.md

Before merging to master I want to think about it a bit more and maybe get some feedback from others, since I personally am not a heavy user of global modules in my own workflow.

**Comment by lostintangent** [comment]
@jasongin Works beautifully from my basic testing :) It might also be nice to have a way to automate this process as part of running `nvs add`.

**Comment by jasongin** [comment]
I merged this feature.

Regarding the suggestion about optionally doing it as part of `nvs add`, that part isn't implemented yet. I opened a new issue to track that at https://github.com/jasongin/nvs/issues/6
