### ISSUE TITLE
Bad NVS_HOME 

### ISSUE THREAD

**Issue by fearthecowboy** [jasongin/nvs#104]
Installed the 1.4.2 MSI
opened up a powershell prompt:

![image](https://user-images.githubusercontent.com/133736/45899450-b5096700-bd91-11e8-92b2-4358a24d97eb.png)

I'm curious why in https://github.com/jasongin/nvs/blob/master/nvs.ps1#L4  you wouldn't just use `$PSScriptRoot`  to get the folder of the script.  I've found that ` $MyInvocation.MyCommand.Path` can be ... inconsistent, especially across powershell versions.

**Comment by jasongin** [comment]
I've been using `$MyInvocation.MyCommand.Path` in PS scripts for a long time and never saw any issues. Do you know why or how it is inconsistent?

I was not aware of `$PSScriptRoot`. Apparently it was added in PowerShell 3.0. It's _probably_ OK for nvs to use that, since 3.0 goes back to Windows 7 SP1.

**Comment by fearthecowboy** [comment]
Why? "Because PowerShell" 😁 

I've had troubles where I see a different result if it was run via a new instance of `powershell.exe`  (ie, `powershell foo.ps1` )  and just from an open instance.  

I'm not sure in __this case__ *why* it decided to go awry. 

But, yeah, if anyone isn't using at least PS 3.0, they have a lot of other problems at the same time.

**Comment by fearthecowboy** [comment]
Fixed by #105 .

Thanks!
