### ISSUE TITLE
Does not seem to work with lts/boron and others

### ISSUE THREAD

**Issue by DanielRuf** [jasongin/nvs#107]
On TravisCI it fails with `lts/boron` and others.

https://travis-ci.org/zurb/foundation-sites/jobs/441371101#L39

**Comment by jasongin** [comment]
`nvs add lts/boron` is incorrect usage. When specifying a two-part version, the part to the left of the slash refers to a "remote" (or a "fork") of node, one of those configured in `setings.json`. See also https://github.com/jasongin/nvs/blob/master/doc/ADD.md

When you run that command, NVS prints out an error message: `Error: Remote name not found in settings.json: lts`. I don't know why that message wasn't captured in the Travis-CI log.

In this case, what you wanted was `nvs add node/boron`, or just `nvs add boron` (since `node` is the default remote).

**Comment by DanielRuf** [comment]
> `nvs add lts/boron` is incorrect usage.

Well this is what TravisCI uses.

**Comment by DanielRuf** [comment]
See https://travis-ci.community/t/windows-instances-hanging-before-install/250

**Comment by jasongin** [comment]
Fixed in `nvs@1.5.0`.
https://github.com/jasongin/nvs/releases/tag/v1.5.0

I decided it will be easier for everyone if nvs can just be smarter and recognize that LTS version syntax, which people coming from nvm are likely to use.
