### ISSUE TITLE
Idea: split into 2 parts to solve the chicken and egg problem

### ISSUE THREAD

**Issue by brodybits** [jasongin/nvs#14]
1. Platform-specific scripts that automatically fetches the most recent lts version and does the installation (mostly *shell scripts)
2. User-invoked nvs command scripts for version management

To take it even further: we could have a node version management "stack" with layers for installation shell scripts, node management command scripts, and a possible GUI layer.

**Comment by jasongin** [comment]
Part of the shell scripts could be factored out that way. But the split wouldn't be clean because the nvs platform-specific shell scripts do more than just download the private node binary. Other functionality includes:
 * Updating the environment (PATH) of the calling shell.
 * Hooking into the prompt/cd shell functions to enable auto switching per-directory.
 * Forwarding the current node version selection to a sudo environment (`nvsudo` command).
 * Initializing PATH to include the default version when sourced (on login).

Now perhaps all of that functionality could also be used by other JS version-management tools. But do we really expect there to be a need for more than one JS-based tool?

**Comment by jasongin** [comment]
Closing this old issue because I don't expect to do anything about it, for reasons explained above.
