### ISSUE TITLE
Rm command doesn't seem to support the same flexible version syntax as other commands

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#19]
The `nvs rm` command doesn't seem to allow omitting the patch component in the specified version argument. However, if you use it this way, it actually prints an output string which makes it appear to have worked, even though it didn't. The following image illustrates the behavior of the `add`, `ls` and `use` commands, and the inconsistent behavior of the `rm` command:

<img width="325" alt="screen shot 2016-11-27 at 11 10 44 am" src="https://cloud.githubusercontent.com/assets/116461/20651048/4ad5ccd4-b492-11e6-827d-236998a8a58d.png">

Additionally, I can confirm that the same behavior happens if you provide just a major component (e.g. `7` instead of `7.1`). All of the other commands work as expected, however, the `rm` command doesn't.

As soon as I specify the full version string (e.g. `7.1.0`), then the `nvs rm` command works as expected. However, the output that is provides in this case is the exact same as with the major and major/minor attempts, so from the end-users perspective, it's not possible that actually determine if it worked, aside from running `nvs ls` to see if it's still installed.

**Comment by lostintangent** [comment]
This is likely related to the previous issue, but I also just noticed that the `nvs rm` command doesn't allow simply specifying a remote note:

<img width="844" alt="screen shot 2016-11-27 at 11 20 34 am" src="https://cloud.githubusercontent.com/assets/116461/20651116/a6280ede-b493-11e6-934c-f5a8f2376ffd.png">

For nightly remotes, it would be ideal to be able to add and then remove it, since I'll likely only ever have one version installed at most, and so I don't really care what the version is. I love how the `add`, and `use` commands seem to behave by appending `/latest` to the version string when you simply provide it with a remote name.

**Comment by jasongin** [comment]
Originally I had thought that `rm` should always require a complete explicit version string to ensure it didn't infer something that wasn't intended. But it's better to be consistent with the other commands. So now it resolves partial versions and remote names the same way as the other commands.

It will still attempt to remove a version that is not successfully resolved (does not show up in `nvs ls`), in case there is a need to clean up after a partially-extracted or partially-deleted version.

I also fixed the output, so that if there is nothing to remove then it doesn't output a misleading line that makes it look like it did some work, as it did before.

Fixed in https://github.com/jasongin/nvs/commit/085d6bdf31f91022686e2899eece1c7f9f5f6573
