### ISSUE TITLE
[Windows Installation] - Path update variable is incorrect

### ISSUE THREAD

**Issue by bozzelliandrea** [jasongin/nvs#243]
During installation, the env variable path is updated with "c:\".
The correct case for Windows is C with uppercase.

**Comment by jasongin** [comment]
Are you installing on windows using the MSI package? If so, the value added to PATH comes [from the MIS's INSTALLDIR property](https://github.com/jasongin/nvs/blob/e61130f76e9e07e8c0201ad9a79ec70bb714c0a0/setup/nvs.wxs#L149). So if anything the bug is from Windows Installer.

If using the `nvs install` command, the value added to PATH is derived [from the Node.js `__dirname` keyword](https://github.com/jasongin/nvs/blob/e61130f76e9e07e8c0201ad9a79ec70bb714c0a0/lib/install.js#L22).

Either way, I think this is not a bug in `nvs`. But it doesn't really matter anyway.

**Comment by bozzelliandrea** [comment]
@jasongin yes I'm using the .msi installer, probably it's not a bug of nvs, but can we manage it? I think in the case of Windows (I don't know with other OS, but probably the same behaviour) we need to force the partition character in uppercase.
If you agree i can make the fix.

**Comment by jasongin** [comment]
I think the MSI `INSTALLDIR` property comes from some system environment variables. Can you check whether you have any user or system env variables with lowercase `c:\` ?

I don't know how you'd override it in the installer, since there is no code, it's just declarative.

**Comment by bozzelliandrea** [comment]
i have checked the env variables, but nothing strange and nothing in lowercase, wich version of WiX are you using for the setup wizard? (just for read the correct docs).
Proably another step can be created with the input field for the path, so the user can modify and check if the installation path is correct.
it's just a workaround but this willl work in every OS.

**Comment by jasongin** [comment]
I can't reproduce this issue. When I install on Windows with the MSI, the value added to path is `C:\Users\<username>\AppData\Local\nvs\`, with uppercase `C`.

I still don't understand why it's important. But if you want, I think the next step to diagnose this would be to look at the MSI verbose log:
```
msiexec /i nvs.msi /L*v "install.log"
```

Then look for log messages about how `INSTALLDIR` is set.

**Comment by bozzelliandrea** [comment]
I close the issue, I have tried on another machine and it works fine, it seems more like a problem for my user, thanks for the support.
