### ISSUE TITLE
Installation issue (zsh): "no matches found: -#"

### ISSUE THREAD

**Issue by ucabgao** [jasongin/nvs#27]
I tried to install nvs on macOS Sierra 10.12.3 with zsh 5.3.1, following your instruction:
### Mac, Linux
Specify the installation path, clone the repo, and *source* the `install` command:
```
export NVS_HOME="$HOME/.nvs"
git clone https://github.com/jasongin/nvs "$NVS_HOME"
. "$NVS_HOME/nvs.sh" install
```

After I sourced the install command, I encountered this issue:
```
Downloading bootstrap node from https://nodejs.org/dist/v6.9.4/node-v6.9.4-darwin-x64.tar.xz
nvs:39: no matches found: -#
mv: rename /Users/foo/.nvs/cache/node-v6.9.4-darwin-x64/bin/node to /Users/foo/.nvs/cache/node: No such file or directory
rm: /Users/foo/.nvs/cache/node-v6.9.4-darwin-x64: No such file or directory
Failed to download boostrap node binary.
```

**Comment by jasongin** [comment]
@ucabgao I'm mostly unfamiliar with zsh, but with a bit of online research I found this is related to the `extended_glob` option in zsh, which causes `#` to be treated as a special character related to filename globbing. If I run these commands in zsh then I can reproduce your issue:

```
setopt extended_glob
. "$NVS_HOME.sh" install
```

So you can resolve the problem by clearing that option:
```
unsetopt extended_glob
```

Or since the problematic line in the `nvs.sh` script is a `curl` command, as an alternative to clearing the option you could also workaround it like this:
```
alias curl='noglob curl'
```

I'll look into updating the NVS script so that zsh users don't hit this problem in the future.

**Comment by ucabgao** [comment]
Thanks for the prompt reply.

**Comment by jasongin** [comment]
Reopening because I want to use this issue to track the fix to the script to avoid this problem in the future. And meanwhile if anyone else encounters this they can find the workaround more easily.

**Comment by jasongin** [comment]
Fixed as https://github.com/jasongin/nvs/commit/e8dff87a70a6ed873bdb6e7480c22ce88285cada
