### ISSUE TITLE
Getting "Platform package not available for version: node/7.5.0/arm" on RP2

### ISSUE THREAD

**Issue by codefoster** [jasongin/nvs#28]
I'm attempting to use NVS to maintain node on an RP2 but when I attempt to install any version of node I get "Platform package not available for version: node/<version>/arm". Is this supposed to work, or is this an expected error?

**Comment by jasongin** [comment]
I haven't had an arm system available to test with yet...

It looks like this bug is related to https://github.com/nodejs/node/issues/9491, so something like the workaround described there needs to be applied in the NVS code. Can you try it? Add another case to the `_standardArchName()` function in `nvs/lib/version.js`:

```javascript
   case 'arm':
      return 'armv' + process.config.variables.arm_version + 'l';
```

Note the lowercase-L suffix. I don't know why the [node builds](https://nodejs.org/dist/v7.5.0/) use that.

I suspect this might not work for arm64, but I believe RP2 is armv7. Let me know if this resolves the problem for you.

**Comment by jasongin** [comment]
Thanks for confirming! I merged the PR.
