### ISSUE TITLE
Question regarding labels

### ISSUE THREAD

**Issue by jasonkarns** [jasongin/nvs#33]
I have a question regarding how labels are used with the `use` command.

The docs state that a version must already have been added with `add` before the `use` command can be used. Which implies that `use` works entirely offline. Is this correct? Which means a label (such as `latest` or `lts`) will only refer to the latest node _on the user's machine_?

Scenario:

1. User installs latest lts: `nvs add lts` (which, for this scenario, let's say is 6.0.0)
2. User does some work and switches to another node: `nvs use 5.0`
3. A new v6 is released (let's say, 6.1.0) so latest lts is now 6.1.0
4. User wants to switch back to lts: `nvs use lts`

What happens for step 4? Does it just activate the "latest" lts they have locally available (6.0)? Or does it check online, know that 6.1 is latest lts, and emit an error or warning? Since 6.1 hasn't been added, I presume that it won't automatically download 6.1.

I'm assuming it does the former. Which means there's just a disconnect between how the labels work for `add` vs `use` (not so much a disconnect, as a wrinkle to be aware of).

I'm one of the maintainers of nodenv and would love to chat sometime about some of the more edge-case scenarios; if you'd be willing.

**Comment by jasongin** [comment]
Yes, `nvs use` works entirely offline: it never checks for newer versions or downloads anything.

When a node version is first downloaded with `nvs add`, its LTS status is cached along with the LTS tag, e.g. "Boron". You can see LTS tags in the output of `nvs ls`. Then when you `nvs use lts`, it just selects the latest already-downloaded version that has an LTS tag.

I acknowledge that it is a slight disconnect in how "lts" can mean something different between `nvs add` and `nvs use`, depending on how you think about it. But after carefully considering the options, I thought this behavior allowed for the best balance of usability and functionality.

If `nvs use lts` always checked for a newer version and printed an error when it wasn't downloaded, that would be disruptive if a command that worked for a while suddenly stopped working. Note partial version numbers have similar semantics and considerations: `nvs add 6` downloads the latest 6.x release available, while `nvs use 6` uses the latest 6.x version that you have downloaded -- that should not fail (or download another version) just because there was a newer 6.x release.

I'd be happy to chat more sometime.

**Comment by jasonkarns** [comment]
Cool.

> But after carefully considering the options, I thought this behavior allowed for the best balance of usability and functionality.

I agree. Just wanted to confirm, because I've been thinking about the approaches for nodenv as well and we'd have a similar tradeoff.

My email address is public on my github profile, if you wouldn't mind emailing me, so we can coordinate some time.

**Comment by DanielRuf** [comment]
There is often more than one active lts branch. Currently these are 6 and 8.

**Comment by jasongin** [comment]
@DanielRuf Yes. As I said above you just specify "lts" then the latest is picked. If you want a specific LTS branch you can specify its name like "boron" instead.
