### ISSUE TITLE
env NODE_PATH auto setup?

### ISSUE THREAD

**Issue by jankun** [jasongin/nvs#36]
Hi, just as in the title, since I cant find anything about that in the readme-
is NVS setting any env vars- mostly is it setting up a global NODE_PATH for npm?

and thank you for making nvs, I like your solution a lot.

**Comment by ljharb** [comment]
(NODE_PATH should not be used in any form; as it allows you to potentially require non-local dependencies)

**Comment by jasongin** [comment]
NVS does not do anything with NODE_PATH.

From [README.md#version-switching](https://github.com/jasongin/nvs/blob/master/README.md#version-switching):

> When you `nvs use` a version, the `PATH` of the current shell is updated to include that version's bin directory.

**Comment by jasongin** [comment]
Also, since you mentioned `npm`...

`nvs` relies on the `npm` behavior which locates the global modules directory relative to the `node` binary directory: `$BINDIR/../lib/node_modules`, or `$BINDIR/node_modules` on Windows. `nvs` deletes any `NPM_CONFIG_PREFIX` environment variable to prevent it from overriding that behavior. That is how [global modules are separated per node version](https://github.com/jasongin/nvs/blob/master/README.md#global-modules).

I should document that a little better.

**Comment by jankun** [comment]
Thanks for the clarification - makes sense now. I guess I need to dive into
npm docs which I find frustrating and very unclear at best (example: npm
help rebuild - very helpful... )
