### ISSUE TITLE
nvs link default 7.9.0 doesn't do anything

### ISSUE THREAD

**Issue by anthonyettinger** [jasongin/nvs#47]
I run `nvs link default 7.9.0` and nothing happens. If I open a new cmd shell I still see `node -v` giving me `6.10.0`

This is on windows 10.

I'm trying to set the system default version of node to 7.9.0

**Comment by jasongin** [comment]
Try this instead:
```
nvs link 7.9.0
```

See `nvs help link` for more explanation.

The reason the `nvs link default 7.9.0` command didn't return an error is because `default` is a built-in alias for the currently linked version, so you were asking nvs to re-link the already-linked version, which is effectively a no-op. The extra argument on the end was ignored; I'll consider detecting extra command-line args and showing an error or help instead.

**Comment by anthonyettinger** [comment]
i guess the api is different than nvm. In nvm  you can do `nvm alias default v7.9.0`

**Comment by jasongin** [comment]
Aliases are supported (see `nvs help alias`). It's just that "default" is a special built-in alias that always refers to the linked version.

**Comment by anthonyettinger** [comment]
still nothing. tried `nvs link 7.9.0` and get no output and when i open a new terminal I still have v6 as the default.

**Comment by jasongin** [comment]
I see you're on Windows 10. Did you install via the MSI, or some other means? Where is NVS installed? An easy way to find that is `nvs which`, that show the path to the current node version that NVS set up. The install path matters because the `nvs link` behavior can be different depending on whether it is a per-user installation (typically under %LOCALAPPDATA%) or system installation (typically under %ProgramData%).

**Comment by anthonyettinger** [comment]
I installed via the msi.

`C:\Users\Administrator\AppData\Local\nvs\node\7.9.0\x64\node.exe`

**Comment by jasongin** [comment]
Do you have the Node.js (v6) MSI installed separately under Program Files? It's possible that its addition to PATH may be superseding the nvs-configured version when you start a new shell. In the new shell, try running `nvs use` (with no further arguments) to use the default version, and that should fix up the PATH if necessary.

The only reason `nvs link` should show no output is if it doesn't need to do anything because the version you specified is already linked.

For further troubleshooting, can you share your output from `nvs ls` and `nvs alias`?

**Comment by anthonyettinger** [comment]
https://streamable.com/5r7h4

No idea. All I did was follow instructions for nvs on windows. I think it stalled LTS by default which is v6. But I need v7 to test.

**Comment by jasongin** [comment]
From the video, you apparently had a Node.js installation already at `C:\Program Files\IBM\node6`.

If you want `nvs link` to be able to affect the default node version used in a new shell, you'll need to either remove that other Node.js installation, or edit your user or system PATH to remove the reference to that directory.

**Comment by anthonyettinger** [comment]
Ok, thanks.
