### ISSUE TITLE
Eliminate hardcoded dependencies (nit)

### ISSUE THREAD

**Issue by brodybits** [jasongin/nvs#5]
As a nit I would really love to see another solution than the following hard-coded dependencies:
- 7-Zip for Windows
- Node 6.8
- node_modules/progress

I think it *should* be possible to use a prepublish script to keep the 7-Zip and progress dependencies out of the project.

I can think of the following possible alternatives to "Node 6.8":
- minimal node build that leaves out some things such as HTTPS server support, to avoid "insecure" programs hanging around longer than necessary
- something simpler like Duktape, perhaps with "dukluv" to get an API similar to Node.js

Ideal would be to use git rebase and force push to remove 7zr.exe (7-Zip) from the git history. I think it should be relatively safe to do this now if you post a clear notice for the existing nvs hackers.

In general I am extremely happy with this package. Having recently moved from n to nvm I moved to nvs also on my Windows system and got rid of nvm.

**Comment by jasongin** [comment]
I agree in principal, but I think it won't be practical to cleanly eliminate all these. I'll address each of the three...

**7-Zip for Windows**
It could be possible to download this on-demand. (Similar to node.exe, though it could be done in JavaScript.) Currently there isn't a place online where *just* that binary is published, so it would have to be downloaded and extracted from another package, meaning another download and extract delay before Windows users can get started. Or, it could be possible to check for an already-installed 7-Zip in Program Files. But all of this would add a lot of complexity to the bootstrapping process on Windows, and I'm not sure that would be worth it.

Alternatively, it could be possible to use ordinary .zip archives on Windows instead of the .7z archives. The earliest version of NVS did that. But download sizes for .7z archives are significantly smaller, and I found 7-Zip's extraction to be much faster than Windows' built-in zip extraction. So switching to 7-Zip resulted in a much faster version-switching experience.

I generally avoid adding binaries to git repos, but after considering the alternatives I made an exception in this case for 7-Zip. 7zr.exe is actually a stripped-down version of 7-Zip that omits support for all the other various archive formats that the full version of 7-Zip supports. It's only 444 KB.

**Private node binary**
I guess it could be possible to use a somewhat stripped-down version, but there is none readily available to download that I know of. The intention is that nobody should be using that *private* copy of node for anything else, so I wouldn't worry much about more surface area being exposed. Anyway I'm not sure it could be reduced by much. As it is now, the download is only 6-8 MB (depending on OS and CPU architecture), which is not so bad. It could also be possible to detect and use a system-installed node version, to skip the download altogether, but there's more risk there since it's likely to be a different version than what was tested.

**node_modules dependencies**
Initially I wanted to avoid runtime dependencies on any other packages altogether, but as the project grows I think that's unrealistic. Still I do want to strive to keep dependencies minimal. The `progress` module is pretty small, and I considered just writing my own progress-bar code since I'm not entirely happy with that one. But I have plans for more feature development that will be aided by some additional minimal dependencies.

I strongly prefer to avoid the requirement of an `npm install` (or prepublish script) before the tool is usable. Currently the private instance of node is just the binary, with no npm or other external modules. Adding an `npm install` to the bootstrapping process would add more download and install time, more complexity, and more risk for something going wrong. So that's why I chose the approach of checking in runtime module dependencies.

**Comment by brodybits** [comment]
Thanks @jasongin (sorry I missed your response on Sunday). In general your responses do make sense to me. But I still think small improvements can be made if you have the time and patience:

> **7-Zip for Windows**
> It could be possible to download this on-demand. (Similar to node.exe, though it could be done in JavaScript.) Currently there isn't a place online where just that binary is published

Agreed but why not post it somewhere yourself (or maybe let someone else post it for you)?

Another nit with including the 7-Zip is the LGPL license. I think it is better to keep LGPL code/executables out of a project with permissive licensing if possible (though LGPL is not viral).

Yes 440/450 KB is no problem for practical purposes but I think it is the largest artifact in this whole project.

I do agree with your other points about this. What if someone installed 7-Zip but it is the wrong architecture, dev build, or something else?

> **Private node binary**

What I still don't like is that there is executable code that contains OpenSSL code that may have known vulnerabilities. While we know it should not be a problem in practice I think it is best to avoid keeping executable code with known security vulnerabilities running on the system.

Agreed with your other points. I would **not** favor detecting and using the system installed version of node. One more thing that *could* go wrong when we least expect it.

> **node_modules dependencies**

I would favor keeping such embedded dependencies in another place such as `deps` or *maybe* `lib/deps`. Otherwise agreed.

**Comment by jasongin** [comment]
> why not post [7zr.exe] somewhere yourself

I'm open to that approach. I'll add it to the backlog.

> Another nit with including the 7-Zip is the LGPL license.

Actually that's not an issue. While the full version of 7-Zip is LGPL, the `7zr.exe` used in this project is [from the LZMA SDK which is **public domain**](http://7-zip.org/sdk.html). I copied its license notice in the [`readme.txt` checked in alongside it](https://github.com/jasongin/nvs/tree/master/tools/7-Zip).

> I would favor keeping such embedded dependencies in another place such as `deps`

That's probably a good idea. Currently the mixing of dev dependencies and runtime dependencies all under `node_modules` means the `.gitignore` and the MSI setup project need to be updated whenever adding a dependency.

**Comment by brodybits** [comment]
And a final nit (maybe you should call me Brody nits):

The `7zr.exe` artifact would probably remain the biggest artifact in the git history for a while, which would affect installation on *nix platforms unless we do git tricks with a force push to get it out. (The one thing I can think of is if someone repurposes `nvs` for another application over a space link [interstellar space link?].) The workaround would be to tell people to clone with a limited `--depth` value.

I stand corrected regarding 7zr/LZMA license. Thanks again for publishing this, it seems to be the only good cross-platform node version manager solution. To be honest the separate 7zr.exe download would be nice to have someday but not so critical for me. I would rather see #7 (simplify the NVS update experience) fixed first:)
