### ISSUE TITLE
nvs use error

### ISSUE THREAD

**Issue by Eric--** [jasongin/nvs#59]
Hi @jasongin 
I use nvs in windows, I have this error below:
`
$ nvs.cmd use lts
PATH += %LOCALAPPDATA%\nvs\node\6.11.0\x64
'C:\Users\steven\AppData\Local\nvs\nvs_tmp_1015611510.cmd' not inner command or executable command 
`

**Comment by jasongin** [comment]
Do you see that error every time you run `nvs use`? I don't understand how it could happen, because there is a check to see if the file exists, right before calling it. Here is there relevant script code in `nvs.cmd`:
```cmd
:: Call the post-invocation script if it is present, then delete it.
:: This allows the invocation to potentially modify the caller's environment (e.g. PATH).
IF NOT EXIST %NVS_POSTSCRIPT% GOTO :CLEANUP
CALL %NVS_POSTSCRIPT%
DEL %NVS_POSTSCRIPT%

:CLEANUP
```
In your case, `%NVS_POSTSCRIPT%` must have been set to "C:\Users\steven\AppData\Local\nvs\nvs_tmp_1015611510.cmd". 

Maybe you could try removing the `DEL %NVS_POSTSCRIPT%` line from `nvs.cmd` and see if the file actually existed? (It has a different unique name every time.) But then why would the `CALL` command fail if the file exists? Are you able to `CALL` it directly from the command prompt?

**Comment by Eric--** [comment]
thanks for your answers!
I do the change below
```
IF NOT EXIST %NVS_POSTSCRIPT% GOTO :CLEANUP
CALL %NVS_POSTSCRIPT%
:: DEL %NVS_POSTSCRIPT%
```
but not found the 'nvs_tmp_1015611510.cmd' file,
could you tell me where the file was generated?

**Comment by Eric--** [comment]
I found these scripts in this folder

![image](https://user-images.githubusercontent.com/6873556/27617882-b1da7406-5beb-11e7-90e7-830aaa74c8f4.png)

I guess my error here, as it was %LOCALAPPDATA%

**Comment by Eric--** [comment]
I have solved this problem! Thank you very much.

**Comment by jasongin** [comment]
How did you solve it?

That's strange that you have a folder that is literally named "C:\Users\steven\AppData\Local\nvs\%LOCALAPPDATA%\nvs". Apparently at some point the `%LOCALAPPDATA%` variable didn't get expanded like it was supposed to. Was it a mistake in manually setting the `NVS_HOME` environment variable?

**Comment by Eric--** [comment]
Yes I config NVS_HOME manually in windows as usual !  But %LOCALAPPDATA% was not recognized by system.
