### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by brodybits** [jasongin/nvs#78]
I noticed that install from GitHub gives me v1.4.3 with last change made in September while last version in <https://github.com/jasongin/nvs/releases> is v1.4.2 made in July 2017. Can we add a new release tag for 1.4.3?

**Comment by jasongin** [comment]
The change in September was a unix-only bugfix, so I didn't bother creating a GitHub release for that since the releases are primarily used to distribute MSIs for Windows.

I thought I would soon have another soon release anyway. But my development pace on this project has slowed recently as my focus has shifted elsewhere. (I certainly haven't abandoned it though.)

**Comment by jasongin** [comment]
Closing because there have been a few releases since.
