### ISSUE TITLE
Use latest lts as bootstrap?

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [jasongin/nvs#85]
Currently it uses v6.x as bootstrap. What about use latest lts?

**Comment by jasongin** [comment]
Sure, it should update at some point. I think it's not urgent though, since 6.x LTS is still supported for another year, and the bootstrap node version doesn't affect what node versions you can install using the tool. I think the main motivation for me would be to make some of the promise code a bit cleaner using `async`/`await`.

**Comment by jasongin** [comment]
Done. [`nvs@1.5.0`](https://github.com/jasongin/nvs/releases/tag/v1.5.0) uses Node v10.

**Comment by ljharb** [comment]
Note that since node 10 lacks 32 bit support, this change will mean nvs can’t be used on older machines, which according to nvm bug reports, are still in far too frequent use.

**Comment by jasongin** [comment]
Thanks for the info, I wasn't aware of that change in platform support. But I still see 32bit windows builds of Node 10. It looks like just 32bit Linux support was dropped. Are there really that many 32bit Linux users? I could consider going back to node 8 if this is a problem. Or those users can continue to use `nvs@1.4.2`, which still works fine.

**Comment by ljharb** [comment]
there’s not a ton, but nvm has received a few bug reports I’ve sent over to the node people.
