### ISSUE TITLE
Add GraalVM node to nvs?

### ISSUE THREAD

**Issue by EdwardDrapkin** [jasongin/nvs#90]
Hey there,

Are there any plans to add the newly-release GraalVM implementation of Node to NVS?  I'd be glad to help if you point me in the right direction.

Thanks!

**Comment by ljharb** [comment]
What is GraalVM? Can you link to it?

**Comment by EdwardDrapkin** [comment]
It's the new polyglot runtime derived from the JVM: http://www.graalvm.org/

It ships with a drop in replacement for node (if you download Graal, it's in 'bin/node')

**Comment by jasongin** [comment]
I think it probably doesn't make sense for `nvs` to support installing versions of GraalVM, since it's much more than just node. I'm sure the format of published releases / binaries is vastly different.

However, if you do have GraalVM installed separately (or any other `node` binary) you can still use `nvs` [directory aliasing](https://github.com/jasongin/nvs/blob/master/doc/ALIAS.md#aliasing-directories) to easily switch your path.

For example:
```
$ nvs alias graal /path/to/graalvm/bin/node
$ nvs use graal
PATH -= ~/.nvs/node/9.6.1/x64/bin
PATH += /path/to/graalvm/bin/node
```

**Comment by EdwardDrapkin** [comment]
Thanks, I'll just alias it.  Didn't know I could do that!
