### ISSUE TITLE
move to org

### ISSUE THREAD

**Issue by DanielRuf** [jasongin/nvs#94]
It would be good to create an org and move the repo to it.

**Comment by jasongin** [comment]
Hi @DanielRuf,

I'm not opposed to the idea, but can you explain what you think are the reasons / benefits of doing so?

**Comment by DanielRuf** [comment]
Hi, the reasons are better permission management (contributors, collaborators, teams), a higher truckfactor, better cooperation, better separation of projects, easier maintenance, ...

**Comment by jasongin** [comment]
So far there haven't been a lot of people interested in contributing much. If the project was associated with an organization rather than an individual account, then would people perceive it more as a community effort and therefore contribute more?

To be clear, I would more than welcome contributions from others to this project. I personally haven't been able to devote as much time recently as it really needs. The project and users could clearly benefit from maintainers who are more actively engaged.

Last year there was some discussion at [`nodejs/version-management`](https://github.com/nodejs/version-management/) about possibly adopting/promoting a cross-platform version-manager tool, and `nvs` was the obvious candidate. In that scenario, `nvs` might have joined the nodejs org. But that never reached any consensus.

**Comment by brodybits** [comment]
Several contributions seem to be awaiting review, for example: #73, #155, #157
